name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  setTagValues:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      tag_main: ${{ steps.tag_main.outputs.main }}
      tag_patch: ${{ steps.tag_main.outputs.main }}.${{ github.run_number }}
    steps:
      - id: tag_main
        run: echo "main=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: setTagValues
    strategy:
      matrix:
        version: ["${{needs.setTagValues.outputs.tag_main}}", "${{needs.setTagValues.outputs.tag_patch}}"]
    steps:
      - name: did this work
        run: echo "${{ matrix.version }}"

