name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to packagist.org
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update packagist<>github
        run: |
          echo "username: ${{ vars.PACKAGIST_USERNAME }}"
          echo "password: ${{ secrets.PACKAGIST.PASSWORD }}"
          echo "repo url: ${{ github.repository }}"
