name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  set-tag-values:
    runs-on: ubuntu-latest
    outputs:
      tag_main: ${{ steps.tag_main.outputs.main }}
      tag_patch: ${{ steps.tag_main.outputs.main }}.${{ github.run_number }}
    steps:
      - id: tag_main
        run: echo "main=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
  build-and-publish:
    permissions:
      contents: read
      id-token: write
      attestations: write
    runs-on: ubuntu-latest
    needs: set-tag-values
    strategy:
      matrix:
        image_name: ["${{ github.repository }}"]
        version: [latest, "${{needs.set-tag-values.outputs.tag_main}}", "${{needs.set-tag-values.outputs.tag_patch}}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Create tags
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a ${{ matrix.version }} -m "Auto-tag on merge/push"
          git push origin ${{ matrix.version }}
      - name: Log in to Docker Hub
        uses: docker/login-action@ef38ec311a7df3f01475313e7c5bb584b74b112a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - name: Build and push
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./Dockerfile
          push: true
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ matrix.image_name }}:${{ matrix.version }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be
        with:
          subject-name: index.docker.io/${{ matrix.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

