name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  set-tag-values:
    runs-on: ubuntu-latest
    outputs:
      tag_main: ${{ steps.tag_main.outputs.main }}
      tag_patch: ${{ steps.tag_main.outputs.main }}.${{ github.run_number }}
    steps:
      - id: tag_main
        run: echo "main=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
  build-and-publish:
    runs-on: ubuntu-latest
    needs: set-tag-values
    strategy:
      matrix:
        image_name: ["${{ github.repository }}"]
        version: [latest, "${{needs.set-tag-values.outputs.tag_main}}", "${{needs.set-tag-values.outputs.tag_patch}}"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@ef38ec311a7df3f01475313e7c5bb584b74b112a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ matrix.image_name }}:${{ matrix.version }}          
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ matrix.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

