name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Set env vars
    steps:
      - name: Set tag names
        run: |
          echo "TAG_MAIN=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "TAG_PATCH=$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_ENV
  try-it:
    needs: publish
    strategy:
      matrix:
        version: ["${{ TAG_MAIN }}", "${{ TAG_PATCH }}"]
    runs-on: ubuntu-latest
    name: Publish to packagist.org
    steps:
      - name: Update packagist<>github
        run: |
          echo "${{ matrix.version }}"
