name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  set-tag-values:
    runs-on: ubuntu-latest
    outputs:
      tag_main: ${{ steps.tag_main.outputs.main }}
      tag_patch: ${{ steps.tag_main.outputs.main }}.${{ github.run_number }}
    steps:
      - id: tag_main
        run: echo "main=$(date +'%Y%m')" >> "$GITHUB_OUTPUT"
  build-and-publish:
    runs-on: ubuntu-latest
    needs: set-tag-values
    strategy:
      matrix:
        version: [latest, "${{needs.set-tag-values.outputs.tag_main}}", "${{needs.set-tag-values.outputs.tag_patch}}"]
    steps:
      - name: did this work
        run: echo "${{ matrix.version }}"

