name: Publish on release

on:
  workflow_dispatch
  #release:
    #types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to packagist.org
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set tag names
        run: |
          echo "TAG_MAIN=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "TAG_PATCH=$(date +'%Y%m%d').${{ github.run_number }}" >> $GITHUB_ENV
      - name: Update packagist<>github
        run: |
          echo "${{ env.TAG_MAIN }}"
          echo "${{ env.TAG_PATCH }}"
